src/helpers/providers/heavyProvider.ts
=> Set alchemy address back

src/helpers/web3Modal.ts
- since goerli rpc isn't aviable due merge, we're using rpc from env file (alchemy one)
=> fix walletconnect issues with rpc

src/components/PostProcessing/LinkContent.tsx, src/components/PostProcessing/ViewTweetButton.tsx, src/components/PostProcessing/index.tsx, src/stores/PostIdsStatuses.ts
- updated `LinkContent` component
- added new type to `ProcessingPost` state
- added action button
=> Fix pending post button

src/components/BlockchainList/BlockchainPost.tsx, src/components/BlockchainList/PostsList.tsx, src/hooks/useHashParams.ts, src/hooks/useScrollToAnchor.ts, src/index.css
- added a new hook to get hash from the link
- updated `BlockchainPost` layout
- added an additional check to run or not run the scroll hook
https://user-images.githubusercontent.com/5114069/186436578-0c450a57-98ea-4b02-9e7a-a956d99cd412.mov
=> Fix scroll to post logic

src/components/Dropdown/Menu.tsx
- changed style from `left-0` to `right-0`
=> Fix scroll on blockchain tweets page

src/components/Dropdown/Menu.tsx, src/components/Navbar/SocialLinksAndWallet.tsx
=> Hide Delimiter on small screens

src/components/CreatePost/Form.tsx
- Fixed account switching, sorry that didn't push this earlier
- Fixed twitter account switching
=> Fixed some issues with new rejected UI logic

src/components/Button.tsx
=> Remove shadow from default button

src/index.css
=> Changed caret color to primary (blue-500)

package.json, yarn.lock
=> bump frontend-utils

src/components/CreatePost/SelectAsset.tsx, src/components/Dropdown/Menu.tsx, src/components/Dropdown/index.tsx, src/hooks/useContractNames.ts
- displaying names instead of symbols in dropdown
=> add displaying names instead of symbols

src/components/Delimiter.tsx, src/components/Footer.tsx, src/helpers/visibilityClassnames.ts
- updated `visibility` to look the same as in other projects
- updated Footer
=> Fix footer on small then md

package.json, yarn.lock
=> Upgrade constants version

src/components/BlockchainList/Status.tsx
=> fix loading text

src/components/CreatePost/NoBadgesMessage.tsx
- added wrapper to button with link
=> Fix "Add ZK badges" button link area

src/App.tsx, src/components/ScrollToTop.tsx, src/hooks/useScrollToTop.ts, src/pages/Privacy.tsx, src/pages/Terms.tsx
- not wrapping anymore, but using hook component instead
=> change wrapping scrolltotop

src/components/NavTabLink.tsx
- add location for check with `to` path
=> Fix tab bar links

src/sealVerseData.ts
- added Sealcaster to the SealVerse dropdown
=> added sealcaster to sealverse

src/classnames/tailwind.ts, src/components/Navbar/Logo.tsx, tailwind.config.js
=> Fix logo for Safari

src/classnames/tailwind.ts, src/components/Card.tsx, tailwind.config.js
=> Fix inner shadow for cards

package.json, src/components/BlockchainList/Status.tsx, src/helpers/parsePostLogData.ts, src/stores/PostIdsStatuses.ts, src/stores/WalletStore.ts, yarn.lock
- updated contract type package
- updated status component
- updated created & parse functions
- updated Statuses Store
=> Update code to new contract type

package.json, yarn.lock
- update version of the package
=> Update constants version

package.json, src/components/CreatePost/Form.tsx, src/components/TextArea.tsx, yarn.lock
- upgraded `frontend-utils` version
- changed methods to proper ones
---
Todo: run `yarn` to update `.lock` after a new package is published
=> Upgrade utils and change methods to proper one

src/components/BlockchainList/PostsList.tsx, src/hooks/useHashParams.ts
- add `location` to handle changes in the url
=> Fix view post button

src/components/Cookie.tsx
=> Add space to cookie title
